# Generated by Django 3.1 on 2020-09-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Description',
            field=models.TextField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='item',
            name='Image',
            field=models.ImageField(blank=True, upload_to='blog/static/img'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.TextField(max_length=50),
        ),
    ]
