# Generated by Django 3.1 on 2020-09-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200910_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='Image',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
