# Generated by Django 3.1 on 2020-09-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200911_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(default='lp-1.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
