# Generated by Django 3.1 on 2020-09-12 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='title',
        ),
    ]
