# Generated by Django 3.1 on 2020-09-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_orderitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
