# Generated by Django 3.1 on 2020-09-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_orderitem_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='title',
        ),
    ]
