# Generated by Django 3.1 on 2020-09-13 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
