# Generated by Django 3.1 on 2020-09-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_orderitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(default=50.0),
            preserve_default=False,
        ),
    ]
