# Generated by Django 3.1 on 2020-09-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_shopmain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='search',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='search',
            name='created',
        ),
        migrations.AddField(
            model_name='search',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='search',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
