# Generated by Django 3.1 on 2020-09-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20200916_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
