# Generated by Django 3.1 on 2020-09-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_latestproduct_latestproductone_reviewproduct_reviewproductone_topproduct_topproductone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='latestproduct',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='latestproductone',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reviewproduct',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reviewproductone',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='topproduct',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='topproductone',
            name='price',
            field=models.IntegerField(),
        ),
    ]
