# Generated by Django 3.1 on 2020-09-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20200917_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestproduct',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='latestproductone',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reviewproduct',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reviewproductone',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='topproduct',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='topproductone',
            name='price',
            field=models.FloatField(),
        ),
    ]
