# Generated by Django 3.1 on 2020-09-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_pants_shirts_shorts_slippers_watches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=800)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pants',
            options={'verbose_name_plural': 'Pants'},
        ),
        migrations.AlterModelOptions(
            name='shirts',
            options={'verbose_name_plural': 'Shirts'},
        ),
        migrations.AlterModelOptions(
            name='shoes',
            options={'verbose_name_plural': 'Shoes'},
        ),
        migrations.AlterModelOptions(
            name='shorts',
            options={'verbose_name_plural': 'Shorts'},
        ),
        migrations.AlterModelOptions(
            name='slippers',
            options={'verbose_name_plural': 'Slippers'},
        ),
        migrations.AlterModelOptions(
            name='watches',
            options={'verbose_name_plural': 'Watches'},
        ),
    ]
